# Generated by Django 3.1.2 on 2022-06-22 12:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0063_auto_20220611_1431'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialDeal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=100)),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('description', models.TextField(verbose_name='Short Description')),
                ('special_deal_image', models.ImageField(default='specialDeals/specialDeal.jpg', max_length=500, upload_to='specialDeals/imgs/', verbose_name='specialDeal Image')),
                ('additional_image_1', models.ImageField(blank=True, max_length=500, null=True, upload_to='specialDeals/imgs/specialDeal_imgs/', verbose_name='Additional  Image_1')),
                ('additional_image_2', models.ImageField(blank=True, max_length=500, null=True, upload_to='products/imgs/specialDeal_imgs/', verbose_name='Additional  Image_2')),
                ('additional_image_3', models.ImageField(blank=True, max_length=500, null=True, upload_to='products/imgs/specialDeal_imgs/', verbose_name='Additional  Image_3')),
                ('additional_image_4', models.ImageField(blank=True, max_length=500, null=True, upload_to='products/imgs/specialDeal_imgs/', verbose_name='Additional  Image_4')),
                ('valid_form', models.DateTimeField()),
                ('valid_to', models.DateTimeField()),
                ('active', models.BooleanField()),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_update', models.DateTimeField(auto_now=True, null=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='specialDeals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SpecialDealDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('quantity', models.IntegerField()),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='SpecialDealDetail', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('specialDeal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='special_deals.specialdeal')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
