# Generated by Django 3.1.2 on 2022-06-22 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('special_deals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialdeal',
            name='price',
            field=models.FloatField(blank=True, null=True, verbose_name='price'),
        ),
    ]
