# Generated by Django 3.1.2 on 2022-06-23 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('special_deals', '0003_auto_20220623_0627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialdeal',
            name='price',
            field=models.FloatField(blank=True, null=True, verbose_name='Price'),
        ),
    ]
