# Generated by Django 3.1.2 on 2022-06-23 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('special_deals', '0004_auto_20220623_0638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialdeal',
            name='additional_image_2',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='specialDeals/imgs/specialDeal_imgs/', verbose_name='Additional  Image_2'),
        ),
        migrations.AlterField(
            model_name='specialdeal',
            name='additional_image_3',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='specialDeals/imgs/specialDeal_imgs/', verbose_name='Additional  Image_3'),
        ),
        migrations.AlterField(
            model_name='specialdeal',
            name='additional_image_4',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='specialDeals/imgs/specialDeal_imgs/', verbose_name='Additional  Image_4'),
        ),
    ]
