# Generated by Django 3.1.2 on 2022-06-23 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('special_deals', '0005_auto_20220623_0806'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialdeal',
            name='title',
        ),
        migrations.AddField(
            model_name='specialdeal',
            name='ordinal',
            field=models.IntegerField(blank=True, null=True, verbose_name='ordinal'),
        ),
    ]
