# Generated by Django 3.1.2 on 2022-06-23 14:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('special_deals', '0006_auto_20220623_0820'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialdeal',
            name='user',
        ),
        migrations.AddField(
            model_name='specialdeal',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='special_deals', to=settings.AUTH_USER_MODEL),
        ),
    ]
