# Generated by Django 3.1.2 on 2022-06-27 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('special_deals', '0007_auto_20220623_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialdealdetail',
            name='specialDeal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='special_deals.specialdeal'),
        ),
    ]
