# Generated by Django 3.1.2 on 2022-06-29 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('special_deals', '0009_auto_20220628_0634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialdealitem',
            name='specialDeal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='special_deals.specialdeal', verbose_name='specialDeal'),
        ),
    ]
