# Generated by Django 3.1.2 on 2022-07-07 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0030_auto_20220705_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderline',
            name='price',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Price'),
        ),
    ]
