# Generated by Django 3.1.2 on 2022-07-07 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0031_orderline_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='email_client',
        ),
    ]
