# Generated by Django 3.1.2 on 2022-07-06 12:20

from django.db import migrations, models
import django.db.models.deletion
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20220705_1355'),
        ('products', '0064_auto_20220705_1355'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='PRDSKU',
            new_name='SKU',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='content',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='PRDISSale',
            new_name='is_sale',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='PRDSlug',
            new_name='product_slug',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='PRDtags',
            new_name='product_tags',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_description',
            new_name='short_description',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='available',
            new_name='stock_quantity',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='date_update',
            new_name='updated',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='PRDWeight',
            new_name='weight',
        ),
        migrations.RemoveField(
            model_name='product',
            name='PRDDiscountPrice',
        ),
        migrations.RemoveField(
            model_name='product',
            name='PRDISDeleted',
        ),
        migrations.RemoveField(
            model_name='product',
            name='PRDISactive',
        ),
        migrations.RemoveField(
            model_name='product',
            name='PRDPrice',
        ),
        migrations.RemoveField(
            model_name='product',
            name='feedbak_average',
        ),
        migrations.RemoveField(
            model_name='product',
            name='feedbak_number',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_maincategory',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_minicategor',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_subcategory',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_supercategory',
        ),
        migrations.RemoveField(
            model_name='productrating',
            name='PRDIProduct',
        ),
        migrations.AddField(
            model_name='product',
            name='feedback_average',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Feedback average'),
        ),
        migrations.AddField(
            model_name='product',
            name='feedback_number',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Feedback number'),
        ),
        migrations.AddField(
            model_name='product',
            name='length',
            field=models.FloatField(blank=True, null=True, verbose_name='length'),
        ),
        migrations.AddField(
            model_name='product',
            name='published_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='regular_price',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default_currency='SAR', max_digits=12, null=True, verbose_name='Regular Price'),
        ),
        migrations.AddField(
            model_name='product',
            name='regular_price_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('SAR', 'Saudi Riyal'), ('USD', 'US Dollar')], default='SAR', editable=False, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='sale_price',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default_currency='SAR', max_digits=12, null=True, verbose_name='Sale Price'),
        ),
        migrations.AddField(
            model_name='product',
            name='sale_price_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('SAR', 'Saudi Riyal'), ('USD', 'US Dollar')], default='SAR', editable=False, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(blank=True, choices=[('published', 'published'), ('draft', 'draft')], default=True, max_length=13, null=True),
        ),
        migrations.AddField(
            model_name='productrating',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_vendor',
            field=models.ForeignKey(limit_choices_to={'status': 'vendor'}, on_delete=django.db.models.deletion.CASCADE, related_name='product_vendor', to='accounts.profile', verbose_name='Product Vendor'),
        ),
        migrations.AlterField(
            model_name='productrating',
            name='client_name',
            field=models.ForeignKey(blank=True, limit_choices_to={'status': 'customer'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Customer', to='accounts.profile', verbose_name='Client'),
        ),
        migrations.AlterField(
            model_name='productrating',
            name='vendor',
            field=models.ForeignKey(blank=True, limit_choices_to={'status': 'vendor'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendor', to='accounts.profile', verbose_name='Vendor'),
        ),
    ]
