# Generated by Django 3.1.2 on 2022-07-07 13:49

from django.db import migrations, models
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0065_auto_20220706_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(default='products/placeholder.png', max_length=500, upload_to='products/imgs/', verbose_name='Product Image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_slug',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=150, null=True, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='product',
            name='regular_price',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default_currency='SAR', max_digits=12, verbose_name='Regular Price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='regular_price_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('SAR', 'Saudi Riyal'), ('USD', 'US Dollar')], default='SAR', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(blank=True, choices=[('published', 'published'), ('draft', 'draft')], default='published', max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock_quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Stock quantity'),
        ),
    ]
